import type { BuildingDef, StaffDef, StaffKind } from './types';

/**
 * Каталог построек. Названия и набор объектов взяты из оригинальной игры
 * (Gear Games, 2007) — сами ассеты рисуются заново, см. src/render/art.ts.
 */
const list: BuildingDef[] = [
  // ─────────── дороги ───────────
  {
    key: 'road_dirt',
    name: 'грунтовая дорога',
    cat: 'road',
    w: 1,
    h: 1,
    cost: 12,
    upkeep: 0,
    door: { x: 0, y: 0 },
    order: 0,
  },
  {
    key: 'road_stone',
    name: 'каменная дорога',
    cat: 'road',
    w: 1,
    h: 1,
    cost: 34,
    upkeep: 1,
    door: { x: 0, y: 0 },
    scenery: 2,
    sceneryRadius: 2,
    order: 1,
  },

  // ─────────── аттракционы ───────────
  {
    key: 'batut',
    name: 'батут',
    cat: 'ride',
    w: 2,
    h: 2,
    cost: 340,
    upkeep: 20,
    door: { x: 0, y: 1 },
    rating: 18,
    capacity: 2,
    duration: 6,
    basePrice: 4,
    order: 10,
  },
  {
    key: 'kacheli',
    name: 'качели',
    cat: 'ride',
    w: 2,
    h: 2,
    cost: 520,
    upkeep: 26,
    door: { x: 0, y: 1 },
    rating: 27,
    capacity: 2,
    duration: 8,
    basePrice: 6,
    order: 11,
  },
  {
    key: 'tir',
    name: 'тир',
    cat: 'ride',
    w: 2,
    h: 2,
    cost: 720,
    upkeep: 32,
    door: { x: 0, y: 1 },
    rating: 33,
    capacity: 2,
    duration: 7,
    basePrice: 8,
    order: 12,
  },
  {
    key: 'karusel',
    name: 'карусель',
    cat: 'ride',
    w: 3,
    h: 3,
    cost: 950,
    upkeep: 48,
    door: { x: 1, y: 2 },
    rating: 40,
    capacity: 4,
    duration: 10,
    basePrice: 10,
    needsMotor: true,
    order: 13,
  },
  {
    key: 'tarzanka',
    name: 'тарзанка',
    cat: 'ride',
    w: 2,
    h: 3,
    cost: 1250,
    upkeep: 60,
    door: { x: 0, y: 2 },
    rating: 48,
    capacity: 1,
    duration: 8,
    basePrice: 13,
    order: 14,
  },
  {
    key: 'strah',
    name: 'комната страха',
    cat: 'ride',
    w: 3,
    h: 3,
    cost: 1600,
    upkeep: 75,
    door: { x: 1, y: 2 },
    rating: 55,
    capacity: 3,
    duration: 12,
    basePrice: 16,
    order: 15,
  },
  {
    key: 'koleso',
    name: 'колесо',
    cat: 'ride',
    w: 3,
    h: 3,
    cost: 2300,
    upkeep: 110,
    door: { x: 1, y: 2 },
    rating: 66,
    capacity: 6,
    duration: 15,
    basePrice: 20,
    needsMotor: true,
    order: 16,
  },
  {
    key: 'gorki',
    name: 'горки',
    cat: 'ride',
    w: 4,
    h: 3,
    cost: 3600,
    upkeep: 170,
    door: { x: 1, y: 2 },
    rating: 80,
    capacity: 4,
    duration: 13,
    basePrice: 27,
    needsMotor: true,
    order: 17,
  },

  // ─────────── сервисы ───────────
  {
    key: 'istochnik',
    name: 'источник',
    cat: 'service',
    w: 1,
    h: 1,
    cost: 130,
    upkeep: 6,
    door: { x: 0, y: 0 },
    serves: 'thirst',
    servePower: 95,
    capacity: 2,
    duration: 3,
    basePrice: 2,
    order: 20,
  },
  {
    key: 'tualet',
    name: 'туалет',
    cat: 'service',
    w: 2,
    h: 2,
    cost: 420,
    upkeep: 24,
    door: { x: 0, y: 1 },
    serves: 'bladder',
    servePower: 100,
    capacity: 2,
    duration: 6,
    basePrice: 1,
    order: 21,
  },
  {
    key: 'morozh',
    name: 'мороженица',
    cat: 'service',
    w: 2,
    h: 2,
    cost: 480,
    upkeep: 28,
    door: { x: 0, y: 1 },
    serves: 'hunger',
    servePower: 45,
    capacity: 2,
    duration: 5,
    basePrice: 6,
    needsStaff: 'seller',
    order: 22,
  },
  {
    key: 'zakusochnaya',
    name: 'закусочная',
    cat: 'service',
    w: 2,
    h: 2,
    cost: 680,
    upkeep: 36,
    door: { x: 0, y: 1 },
    serves: 'hunger',
    servePower: 95,
    capacity: 3,
    duration: 8,
    basePrice: 9,
    needsStaff: 'cook',
    order: 23,
  },
  {
    key: 'medpunkt',
    name: 'медпункт',
    cat: 'service',
    w: 2,
    h: 2,
    cost: 980,
    upkeep: 44,
    door: { x: 0, y: 1 },
    serves: 'health',
    servePower: 100,
    capacity: 1,
    duration: 9,
    basePrice: 12,
    needsStaff: 'shaman',
    order: 24,
  },
  {
    key: 'dinomotor',
    name: 'диномотор',
    cat: 'service',
    w: 2,
    h: 2,
    cost: 850,
    upkeep: 55,
    door: { x: 0, y: 1 },
    order: 25,
  },

  // ─────────── декорации ───────────
  {
    key: 'skameyka',
    name: 'скамейка',
    cat: 'decor',
    w: 1,
    h: 1,
    cost: 70,
    upkeep: 2,
    door: { x: 0, y: 0 },
    seat: true,
    capacity: 2,
    duration: 12,
    scenery: 2,
    sceneryRadius: 2,
    order: 30,
  },
  {
    key: 'cvety',
    name: 'цветы',
    cat: 'decor',
    w: 1,
    h: 1,
    cost: 35,
    upkeep: 1,
    door: { x: 0, y: 0 },
    scenery: 4,
    sceneryRadius: 3,
    order: 31,
  },
  {
    key: 'kust',
    name: 'куст',
    cat: 'decor',
    w: 1,
    h: 1,
    cost: 55,
    upkeep: 1,
    door: { x: 0, y: 0 },
    scenery: 5,
    sceneryRadius: 3,
    order: 32,
  },
  {
    key: 'derevo',
    name: 'дерево',
    cat: 'decor',
    w: 1,
    h: 1,
    cost: 110,
    upkeep: 2,
    door: { x: 0, y: 0 },
    scenery: 8,
    sceneryRadius: 4,
    order: 33,
  },
  {
    key: 'palma',
    name: 'пальма',
    cat: 'decor',
    w: 1,
    h: 1,
    cost: 150,
    upkeep: 3,
    door: { x: 0, y: 0 },
    scenery: 10,
    sceneryRadius: 4,
    order: 34,
  },
];

export const DEFS: Record<string, BuildingDef> = Object.fromEntries(
  list.map((d) => [d.key, d]),
);

export const ALL_DEFS = list;

/** Радиус покрытия диномотора в клетках. */
export const MOTOR_RADIUS = 6;

export const STAFF: Record<StaffKind, StaffDef> = {
  seller: {
    key: 'seller',
    name: 'продавец',
    duty: 'продаёт товары',
    salary: 130,
    hireCost: 60,
  },
  cook: { key: 'cook', name: 'повар', duty: 'готовит еду', salary: 160, hireCost: 80 },
  repairman: {
    key: 'repairman',
    name: 'ремонтник',
    duty: 'чинит аттракционы',
    salary: 190,
    hireCost: 100,
  },
  guard: {
    key: 'guard',
    name: 'охранник',
    duty: 'следит за порядком',
    salary: 170,
    hireCost: 90,
  },
  shaman: {
    key: 'shaman',
    name: 'шаман',
    duty: 'лечит посетителей',
    salary: 210,
    hireCost: 110,
  },
};

/** Работники, которых нанимают на карту, а не в конкретное здание. */
export const PATROL_STAFF: StaffKind[] = ['repairman', 'guard'];

export const CATEGORY_NAMES: Record<string, string> = {
  road: 'дороги',
  ride: 'аттракционы',
  service: 'сервисы',
  decor: 'растительность',
};
