import type { LevelDef } from './types';

const BASE = ['road_dirt', 'skameyka', 'cvety', 'kust'];

export const LEVELS: LevelDef[] = [
  {
    key: 'ravnina',
    name: 'равнина',
    intro:
      'Ровное место у реки. Проложи дорогу от входа, поставь пару простых аттракционов и не забудь про воду — под солнцем племя быстро мучается жаждой.',
    money: 3200,
    unlocked: [...BASE, 'batut', 'kacheli', 'istochnik', 'tualet', 'derevo'],
    goals: { money: 6500, rating: 45 },
    seed: 1207,
    water: 0.5,
    rocks: 0.3,
  },
  {
    key: 'dinozavry',
    name: 'динозавры',
    intro:
      'Здесь водятся ящеры покрупнее — их запрягают в диномотор. Аттракционы с шестерёнками без него не работают. И гости уже хотят есть.',
    money: 4500,
    unlocked: [
      ...BASE,
      'road_stone',
      'batut',
      'kacheli',
      'tir',
      'karusel',
      'istochnik',
      'tualet',
      'morozh',
      'zakusochnaya',
      'dinomotor',
      'derevo',
    ],
    goals: { money: 13000, rating: 55, visitorsServed: 120 },
    seed: 4488,
    water: 0.8,
    rocks: 0.6,
  },
  {
    key: 'mamonty',
    name: 'мамонты',
    intro:
      'Мохнатые гиганты притащили новые развлечения. Народу больше, аттракционы ломаются чаще — держи ремонтника и охранника наготове.',
    money: 6000,
    unlocked: [
      ...BASE,
      'road_stone',
      'batut',
      'kacheli',
      'tir',
      'karusel',
      'tarzanka',
      'strah',
      'istochnik',
      'tualet',
      'morozh',
      'zakusochnaya',
      'medpunkt',
      'dinomotor',
      'derevo',
      'palma',
    ],
    goals: { money: 22000, rating: 65, rides: 8 },
    seed: 9111,
    water: 1.1,
    rocks: 0.8,
  },
  {
    key: 'plato',
    name: 'плато',
    intro:
      'Каменистое плато. Места мало, скалы мешают, зато сюда добралось колесо обозрения — самая заметная штука в округе.',
    money: 7500,
    unlocked: [
      ...BASE,
      'road_stone',
      'batut',
      'kacheli',
      'tir',
      'karusel',
      'tarzanka',
      'strah',
      'koleso',
      'istochnik',
      'tualet',
      'morozh',
      'zakusochnaya',
      'medpunkt',
      'dinomotor',
      'derevo',
      'palma',
    ],
    goals: { money: 32000, rating: 72, visitorsServed: 400, months: 14 },
    seed: 2024,
    water: 0.4,
    rocks: 1.6,
  },
  {
    key: 'vrata',
    name: 'врата рая',
    intro:
      'Последнее место. Открыты все постройки, включая горки. Собери парк, о котором будут рассказывать у костра ещё сто зим.',
    money: 9000,
    unlocked: [
      ...BASE,
      'road_stone',
      'batut',
      'kacheli',
      'tir',
      'karusel',
      'tarzanka',
      'strah',
      'koleso',
      'gorki',
      'istochnik',
      'tualet',
      'morozh',
      'zakusochnaya',
      'medpunkt',
      'dinomotor',
      'derevo',
      'palma',
    ],
    goals: { money: 55000, rating: 80, months: 16 },
    seed: 777,
    water: 0.9,
    rocks: 0.9,
  },
];

/** Песочница: всё открыто, целей нет. */
export const SANDBOX: LevelDef = {
  key: 'sandbox',
  name: 'свободная игра',
  intro: 'Без целей и ограничений. Строй что хочешь.',
  money: 25000,
  unlocked: LEVELS[LEVELS.length - 1].unlocked,
  goals: {},
  seed: Math.floor(Math.random() * 100000),
  water: 0.8,
  rocks: 0.7,
};

export function levelByKey(key: string): LevelDef {
  return LEVELS.find((l) => l.key === key) ?? SANDBOX;
}
